server:
  port: 9091

# config server 로 http://localhost:8888 지정
spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: myapp
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh